#!/bin/sh

test -d mmtests || { echo "no mmtests"; exit 1; }
test -z "$1" && { echo "no config list given"; exit 1; }

here=`pwd`
if [ -f 'config-tag' ]; then
	echo "Found tag file, using it"
	tag=`cat config-tag | tr -d '\t\n '`
else
	echo "Generating tag from kernel version"
	tag=`uname -r | sed -e 's/-.*$//'`
fi
echo "TAG: $tag"

hostconf="$here/config-m-`hostname`"
fsconf="$here/config-btrfs"
mnt="$here/mmtests/work/testdisk"

cd mmtests
for config in `cat "$here/$1"`; do
	echo "Execute mmtests and config $config"

	if findmnt "$mnt"; then
		echo "Found that $mnt is still mounted, fix it or press Enter to continue"
		read
	fi

	conf="$here/$config"
	if ! [ -f "$conf" ]; then
		if [ -f "$here/mmtests/configs/$config" ]; then
			echo "Using config inside mmtests"
			conf="$here/mmtests/configs/$config"
		else
			echo "Warning: config not found"
		fi
	else
		echo "Using local config file $conf"
	fi

	./run-mmtests.sh -c "$fsconf" -c "$hostconf" -c "$conf" "$tag"

	if findmnt "$mnt"; then
		sudo umount "$mnt"
	fi
done
