#!/bin/sh
# Create filesystem from config settings (type, flags, device)
# Usage: $0 [configs...]

here=`pwd`
hostconf="$here/config-m-`hostname`"
fsconf="$here/config-base"

source "$hostconf"
source "$fsconf"

for arg in "$@"; do
	p=$(readlink -f "$arg")
	echo "Source arg: $arg ($p)"
	source "$p"
done

[ -z "$TESTDISK_FILESYSTEM" ] && { echo "ERROR: no filesystem defined"; exit 1; }
[ -z "$TESTDISK_PARTITION" ] && { echo "ERROR: no partition defined"; exit 1; }

if findmnt "$TESTDISK_PARTITION"; then
	echo "ERROR: Found that $TESTDISK_PARTITION is still mounted, fix it manually"
	exit 1
fi

echo RUN: mkfs."$TESTDISK_FILESYSTEM" $TESTDISK_MKFS_PARAM $TESTDISK_PARTITION $TESTDISK_MKFS_PARAM_SUFFIX
mkfs."$TESTDISK_FILESYSTEM" $TESTDISK_MKFS_PARAM $TESTDISK_PARTITION $TESTDISK_MKFS_PARAM_SUFFIX
