#!/bin/sh

test -d mmtests || { echo "ERROR: no mmtests dir found"; exit 1; }
test -z "$1" && { echo "ERROR: no config list given"; exit 1; }

here=`pwd`
if [ -f 'config-tag' ]; then
	echo "INFO: Found tag file, using it"
	tag=`cat config-tag | tr -d '\t\n '`
else
	echo "INFO: Generating tag from kernel version"
	tag=`uname -r | sed -e 's/-.*$//'`
fi
echo "TAG: $tag"

hostconf="$here/config-m-`hostname`"
fsconf="$here/config-base"
mnt="$here/mmtests/work/testdisk"

cd mmtests
for config in `cat "$here/$1"`; do
	echo "INFO: Execute mmtests and config $config"

	if findmnt "$mnt"; then
		echo "WARNING: Found that $mnt is still mounted, fix it or press Enter to continue"
		read
	fi

	conf="$here/$config"
	if ! [ -f "$conf" ]; then
		if [ -f "$here/mmtests/configs/$config" ]; then
			echo "INFO: Using config inside mmtests"
			conf="$here/mmtests/configs/$config"
		else
			echo "WARNING: config $conf not found"
		fi
	else
		echo "INFO: Using local config file $conf"
	fi

	./run-mmtests.sh -c "$fsconf" -c "$hostconf" -c "$conf" "$tag"

	if findmnt "$mnt"; then
		sudo umount "$mnt"
	fi
done
